version: "3.9"

services:
  sql:
    image: inf25dw1g33/sql:V1
    container_name: car-sql-prod
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_maintenance
      MYSQL_USER: car
      MYSQL_PASSWORD: car
    ports:
      - "3308:3306"  # Porta do MySQL para produção (diferente da de dev)
    volumes:
      - car-mysql-data-prod:/var/lib/mysql

  app:
    image: inf25dw1g33/app:V1
    container_name: car-app-prod
    environment:
      DB_HOST: sql
      DB_PORT: 3306  # Porta interna do MySQL no container
      DB_USER: car
      DB_PASSWORD: car
      DB_NAME: car_maintenance
      NODE_ENV: production
    ports:
      - "8081:8080"  # Porta da aplicação para produção (diferente da de dev)
    depends_on:
      - sql

volumes:
  car-mysql-data-prod:

networks:
  prod_network:
    driver: bridge

